"""
Removed unique constraint on role name

Revision ID: d0e0700dcd8e
Revises: 00757b557b02
Create Date: 2022-07-05 15:14:24.598238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0e0700dcd8e"
down_revision = "00757b557b02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("roles_name_key", "roles", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("roles_name_key", "roles", ["name"])
    # ### end Alembic commands ###
