"""empty message

Revision ID: 83164be03c23
Revises: 96f00d0961d1
Create Date: 2024-07-23 13:18:47.748324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83164be03c23'
down_revision = '96f00d0961d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('state_message', sa.TEXT(), nullable=True))
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('state_message')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
