"""
Rename dag_run_id column to run_id in executions table

Revision ID: 999b98e24225
Revises: 991b98e24225
Create Date: 2024-04-08 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abc123456789"
down_revision = "991b98e24225"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.alter_column("dag_run_id", new_column_name="run_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.alter_column("run_id", new_column_name="dag_run_id")

    # ### end Alembic commands ###
