"""empty message

Revision ID: cef1df240b27
Revises: abc123456789
Create Date: 2025-07-22 19:05:11.146449

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef1df240b27'
down_revision = 'abc123456789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dag_run_id', sa.String(length=256), nullable=True))
        batch_op.drop_column('run_id')

    op.rename_table("deployed_dags", "deployed_workflows")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("run_id", sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column("dag_run_id")

    # Rename table back from deployed_workflows to deployed_dags
    op.rename_table("deployed_workflows", "deployed_dags")

    # ### end Alembic commands ###
