"""empty message

Revision ID: cef1df240b27
Revises: abc123456789
Create Date: 2025-07-22 19:05:11.146449

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef1df240b27'
down_revision = 'abc123456789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table("deployed_dags", "deployed_workflows")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Rename table back from deployed_workflows to deployed_dags
    op.rename_table("deployed_workflows", "deployed_dags")

    # ### end Alembic commands ###
