version: '3'

services:
  cornflow:
    build:
      context: ./cornflow-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - CORNFLOW_DB_HOST=cornflow_db
      - CORNFLOW_DB_PORT=5432
      - CORNFLOW_DB_USER=cornflow
      - CORNFLOW_DB_PASSWORD=cornflow
      - CORNFLOW_DB=cornflow
      - AUTH_TYPE=2
      - LDAP_HOST=ldap://openldap:389
      - LDAP_BIND_DN=cn=admin,dc=example,dc=org
      - LDAP_BIND_PASSWORD=admin
      - LDAP_SERVICE_BASE=ou=service,dc=example,dc=org
      - CORNFLOW_SERVICE_USER=cornflow
    depends_on:
      - cornflow_db
      - webserver

  cornflow_db:
    image: postgres
    environment:
      - POSTGRES_USER=cornflow
      - POSTGRES_PASSWORD=cornflow
      - POSTGRES_DB=cornflow
    volumes:
      - postgres_cf_data:/var/lib/postgresql/data/

  webserver:
    build:
      context: ./cornflow-server/airflow_config
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./cornflow-dags/DAG:/usr/local/airflow/dags
      - ./cornflow-dags/requirements.txt:/requirements.txt
      - ./cornflow-server/airflow_config/plugins:/usr/local/airflow/plugins
    environment:
      - AIRFLOW_DB_HOST=airflow_db
      - AIRFLOW_DB_PORT=5432
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
      - AIRFLOW_DB=airflow
      - AIRFLOW_LDAP_ENABLE=True
      - AIRFLOW_LDAP_URI=ldap://openldap:389
      - AIRFLOW_LDAP_SEARCH=ou=users,dc=example,dc=org
      - AIRFLOW_LDAP_BIND_USER=cn=admin,dc=example,dc=org
      - AIRFLOW_LDAP_BIND_PASSWORD=admin
      - AIRFLOW_LDAP_UID_FIELD=cn
    ports:
      - 8080:8080
    depends_on:
      - airflow_db
      - openldap
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 5

  airflow_db:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_af_data:/var/lib/postgresql/data/

  openldap:
    image: osixia/openldap
    command: --copy-service
    container_name: openldap
    hostname: openldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./cornflow-server/airflow_config/ldapbootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif:ro
    environment: 
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - 8081:80
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on: 
      - openldap

volumes:
  postgres_cf_data:
  postgres_af_data:
