"""
Added checks to execution data to store solutions checks

Revision ID: 05699e0071ec
Revises: f3bee20314a2
Create Date: 2022-02-08 15:38:58.304464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "05699e0071ec"
down_revision = "f3bee20314a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "executions",
        sa.Column("checks", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("executions", "checks")
    # ### end Alembic commands ###
