"""
Added checks to solution to execution and solution table

Revision ID: a0d73f79c8ef
Revises: f3bee20314a2
Create Date: 2022-02-08 18:23:37.830052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a0d73f79c8ef"
down_revision = "f3bee20314a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cases",
        sa.Column(
            "solution_checks", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "executions",
        sa.Column("checks", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("executions", "checks")
    op.drop_column("cases", "solution_checks")
    # ### end Alembic commands ###
