"""
Modified state columns in executions table

Revision ID: a472b5ad50b7
Revises: e1a50dae1ac9
Create Date: 2021-01-21 13:25:45.815775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a472b5ad50b7'
down_revision = 'e1a50dae1ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('state', sa.SmallInteger(), nullable=False, server_default=sa.text('0')))
    op.add_column('executions', sa.Column('state_message', sa.TEXT(), nullable=True))
    op.create_check_constraint('check_status_less_than', 'executions', 'state <= 1')
    op.create_check_constraint('check_status_greater_than', 'executions', 'state >= -1')
    op.drop_column('executions', 'finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_status_less_than', 'executions', type_='check')
    op.drop_constraint('check_status_greater_than', 'executions', type_='check')
    op.drop_column('executions', 'state_message')
    op.drop_column('executions', 'state')
    op.add_column('executions',
                  sa.Column('finished', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                            nullable=False))
    # ### end Alembic commands ###
