name: Notify slack

on:
  push

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-18.04
    steps:
      - name: Send custom JSON data to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-message: "Deployed new version of"
          channel-id: 'cornflow'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
