name: integration

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 21
      matrix:
        python-version: [ 3.7, 3.8 ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Clone cornflow server repo
        uses: actions/checkout@master
        with:
          repository: baobabsoluciones/cornflow-server
          ref: master
          path: ./cornflow-server
      - name: Clone dags from cornflow dags public repo
        uses: actions/checkout@master
        with:
          repository: baobabsoluciones/cornflow-dags-public
          ref: main
          path: ./dags
      - name: Copy DAG files
        run: |
          cp -r dags/DAG/* cornflow-server/airflow_config/dags/
          cp dags/requirements.txt cornflow-server/airflow_config/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install .
      - name: Install airflow
        run: |
          python -m venv afvenv
          source afvenv/bin/activate
          AIRFLOW_VERSION=2.2.1
          PYTHON_VERSION="$(python3 --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
          CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
          python -m pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
          python -m pip install -U orloge pulp
          python -m pip install -U git+https://github.com/baobabsoluciones/cornflow-client@master
          python -m pip install -U -r cornflow-server/airflow_config/requirements.txt
          airflow db init
          airflow users create -u admin -f admin -l admin -r Admin -p admin -e admin@example.org
          airflow webserver -p 8080 &
          airflow scheduler &
          deactivate
          sleep 5s
        env:
          AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: 0
          AIRFLOW_HOME: cornflow-server/airflow_config
          AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 0
          AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
          AIRFLOW__WEBSERVER__SECRET_KEY: e9adafa751fd35adfc1fdd3285019be15eea0758f76e38e1e37a1154fb36
          AIRFLOW__CORE__LOAD_EXAMPLES: 0
          AIRFLOW_CONN_CF_URI: http://airflow:Airflow_test_password1@localhost:5050
      - name: Run cornflow
        run: |
          cd cornflow-server
          python -m venv cfvenv
          source cfvenv/bin/activate
          python -m pip install -U -r requirements.txt
          flask db upgrade
          flask access_init -v 0
          flask register_deployed_dags -r http://127.0.0.1:8080 -u admin -p admin -v 0
          flask create_admin_user -u admin -e admin@cornflow.org -p Adminpassword1! -v 0
          flask create_service_user -u airflow -e airflow@cornflow.org -p Airflow_test_password1 -v 0
          flask create_base_user -u user -e user@cornflow.org -p UserPassword1! -v 0
          flask register_dag_permissions -o 1 -v 0
          flask run -p 5050 &
          deactivate
          sleep 5s
        env:
          FLASK_ENV: testing
          FLASK_APP: cornflow.app
          AIRFLOW_URL: http://127.0.0.1:8080
          AIRFLOW_USER: admin
          AIRFLOW_PWD: admin
          SECRET_KEY: THISNEEDSTOBECHANGED
          OPEN_DEPLOYMENT: 1
          AUTH_TYPE: 1
      - name: Run integration tests
        run: |
          coverage run --source=./cornflow_client/ -m unittest discover -s cornflow_client/tests/integration
          coverage run -a --source=./cornflow_client/ -m unittest discover -s cornflow_client/tests/unit
          coverage report -m